
name: "2025 desktop choco packages CI workflow"

on:
  push:
    branches: [ main ]
  schedule:
      - cron:  '39 11 * * *' ##execution of a task in the first minute of the month



jobs:

  windows-2025-pwsh-choco: 
    name: "2025 choco packages"  
    runs-on: windows-2025
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: "check if server is virtual"
      run: Systeminfo | findstr /i model   

    #The wmic (Windows Management Instrumentation Command-line) utility has been deprecated by Microsoft
    # - name: "check the PROCESSOR_ARCHITECTURE environment variable.64-bit systems will say AMD64 and 32-bit systems should say x86"
    #   run: wmic OS get OSArchitecture   
    - name: "check the PROCESSOR_ARCHITECTURE environment variable.64-bit systems will say AMD64 and 32-bit systems should say x86"
      run: Get-CimInstance -ClassName Win32_OperatingSystem | Select-Object OSArchitecture
      shell: pwsh  
    
    - name: "osfingerprinting"
      run: systeminfo | more  
    
      #The wmic (Windows Management Instrumentation Command-line) utility has been deprecated by Microsoft
    # - name: "display all processes, executable path"
    #   run: wmic process list full  
    - name: "display all processes, executable path"
      run: Get-Process | Select-Object ProcessName, Path
      shell: pwsh  
      
      
    - name: "list of running services"
      run: tasklist         
    - name: "list of all processes along with their corresponding PID, and services that are tied to them"
      run: tasklist /svc  
    - name: "look for unusual services"
      run: net start                       
    - name: "query unusual services"
      run: sc query  
      
    - name: "Choco packages - pwsh script" 
      run: .\scripts\Choco_Packages_Desktop_windows10.ps1
      shell: pwsh
    - name: "list installed choco packages"
      run: choco list
      shell: pwsh
  

    

      
 
