name: "2025 desktop DSC packages CI workflow"

on:
  push:
    branches: [ test ]
  schedule:
    - cron: '39 11 * * *'

jobs:
  windows-2025-pwsh-dsc:
    name: "2025 DSC packages"
    runs-on: windows-2025
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: "Apply DSC Configuration"
      run: |
        # Import the DSC resources if they are not already available
        Install-Module -Name PSDscResources, cChoco -Force
        
        # Run the DSC configuration to generate the MOF file.
        # This assumes your script contains 'Configuration DesktopPackages'
        # and will create a directory with that name.
        .\scripts\Apply_DSC_Desktop_Config.ps1
        
        # Apply the DSC configuration by pointing to the newly created folder.
        # The directory name is the name of the Configuration block, not the script name.
        Start-DscConfiguration -Path .\DesktopPackages -Wait -Verbose
      shell: pwsh