name: "2025 desktop DSC packages CI workflow"

on:
  push:
    branches: [ test ]
  schedule:
    - cron: '39 11 * * *'

jobs:
  windows-2025-pwsh-dsc:
    name: "2025 DSC packages"
    runs-on: windows-2025
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Install DSC Modules
      run: |
        Install-Module -Name PSDscResources, cChoco -Force
      shell: powershell
      
    - name: Compile DSC Configuration
      run: |
        # Dot-source the DSC script to load the Configuration block
        . .\scripts\Apply_DSC_Desktop_Config.ps1
        
        # Call the configuration function to compile the MOF file
        DesktopPackages
      shell: powershell
      
    - name: Apply DSC Configuration
      run: |
        # This command will now find the 'DesktopPackages' directory
        Start-DscConfiguration -Path .\DesktopPackages -Wait -Verbose
      shell: powershell
      
    - name: Verify Installations
      run: |
        Write-Host "--- Verifying package installations ---"
        
        # Verify Git installation
        Write-Host "Checking Git version..."
        git --version
        
        # Verify 7-Zip installation
        Write-Host "Checking 7-Zip is available..."
        Get-Command 7z.exe
        
        # Verify Notepad++ installation
        Write-Host "Checking Notepad++ is available..."
        Get-Command notepad++.exe
        
        # Verify Google Chrome installation
        Write-Host "Checking Google Chrome is available..."
        Get-Command chrome.exe
      shell: powershell