name: "2025 desktop DSC packages CI workflow"

on:
  push:
    branches: [ test ]
  schedule:
    - cron: '39 11 * * *'

jobs:
  windows-2025-pwsh-dsc:
    name: "2025 DSC packages"
    runs-on: windows-2025
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Install DSC Modules
      run: |
        Install-Module -Name PSDscResources, cChoco -Force
      shell: pwsh
      
    - name: Compile DSC Configuration
      run: |
        # Dot-source the DSC script to load the Configuration block
        . .\scripts\Apply_DSC_Desktop_Config.ps1
        
        # Call the configuration function to compile the MOF file
        # This is what creates the 'DesktopPackages' directory.
        DesktopPackages
      shell: pwsh
      
    - name: Apply DSC Configuration
      run: |
        # This command will now find the 'DesktopPackages' directory
        Start-DscConfiguration -Path .\DesktopPackages -Wait -Verbose
      shell: pwsh